feat: support Example section for google docstring
rr-/docstring_parser pull request #60
Opened 2021-11-05 03:48 UTC by gfyts0123

2021-11-05 08:40 UTC, rr- requested changes
Thank you for the pull request.

- Let's rename DocstringExamples to DocstringExample
- Let's add missing tests
- Please run black
- Please change `var # type hint` to a `var: TypeHint`

2021-11-07 03:44 UTC, gfyts0123 commented
Thank you for the reply, I have submitted it again.
If there are still any questions, please let me know.

2021-11-07 10:25 UTC, rr- requested changes
Thanks for the changes. A couple of comments left:

Let's remove the assertions on `docstring.meta`.
Let's change the assertions on `test_empty_example` from `docstring.meta` to `docstring.examples`.

2021-11-07 10:25 UTC, rr- commented on docstring_parser/common.py
> +    def examples(self) -> T.Optional[DocstringDeprecated]:
`T.List[DocstringExample]`

2021-11-08 02:18 UTC, gfyts0123 commented
Thanks for the reply, I've changed it.
If there are still any questions, please let me know.

2021-11-08 08:53 UTC, rr- commented
It's still `T.Optional`, whereas the function returns a list :) Please update it to `T.List` and we should be good to go.

2021-11-08 08:54 UTC, rr- requested changes
^

2021-11-09 04:02 UTC, gfyts0123 commented
Oh I found it, thanks for figuring it out, it should be OK now.

2021-11-09 08:37 UTC, rr- approved these changes

2021-11-09 08:40 UTC, rr- commented
Merged manually. Thanks.

2021-11-09 08:40 UTC, closed without merging