Remove deprecated and to be removed (in 3.14) old Ast classes
rr-/docstring_parser pull request #91
Opened 2024-12-04 05:12 UTC by fedepell

Ast.Num, Ast.Str and Ast.NameConstant are deprecated since 3.8 and are removed in (early beta already) 3.14 as per https://docs.python.org/3/library/ast.html#ast.AST and Ast.Constant should be used.

I'm not sure if you strive for maintaining some backwards compatibility (pre 3.8 then?) in which case Maybe we'd need to elaborate additionally the MR with some versions checks.

2025-07-08 06:31 UTC, mauvilsa requested changes
Thank you for contributing!

Just because these classes will be removed in 3.14, it does not mean they are not needed in old python versions. So this should be conditional. Something like: if lower than python version that introduced the deprecation warning, compare against all classes, otherwise only against Constant.

Also please rebase on top of master and make sure that pre-commit runs for your changes.

2025-07-08 09:21 UTC, mauvilsa commented
Actually, having only `ast.Constant` already works on Python 3.8, which is the oldest version currently supported. So no need to be conditional. But, the `ast_constant_attr` part no longer makes sense and should be removed. @fedepell can you do these changes?

2025-07-09 08:12 UTC, merged

2025-07-09 09:28 UTC, LecrisUT commented
From what I've heard, python 3.14 has many non-trivial breakages, one of which that I found out is related to annotations. Please add a CI runner for 3.14. It might require including [`allow-pre-releases`](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#allow-pre-releases) to `actions/setup-python`

2025-07-09 12:37 UTC, mauvilsa commented
This was just about removing deprecation warnings. Not about adding support for Python 3.14.

2025-07-09 12:52 UTC, LecrisUT commented
Indeed. Just saying that this support should be tracked. It's a soft blocker for packaging to Fedora

2025-07-09 14:58 UTC, mauvilsa commented
@LecrisUT would you work on a pull request to add support for 3.14?

2025-07-10 04:43 UTC, fedepell commented
@mauvilsa : sorry for the late response, just back from leave ;) Thanks for the merge and for the additional fixes, looking forward for the next release!

For Python 3.14 I can try to give a hand in adding/testing if needed!

2025-07-10 05:12 UTC, mauvilsa commented
@fedepell this is a community effort. Feel free to open a pull request for Python 3.14 support.

2025-07-10 06:43 UTC, LecrisUT commented
@fedepell Indeed would appreciate someone else taking this one on. I can offer a reference for how pydantic is handling the annotation transition: https://github.com/pydantic/pydantic/pull/11991. And also can be a wall you can bounce opinions off of, but otherwise I would have random time to look into these issues actively.

2025-07-10 08:02 UTC, mauvilsa commented
`docstring-parser` is a rather simple package unlike `pydantic`. I don't think there should be many issues if any for things to work in 3.14. But anyway remains to be seen by whomever works on it.